//! Deterministic standards matrix generated from the embedded coverage ledger.

use std::path::Path;

const HEADER: &str = "<!-- Generated by `lgtm policy docs`; do not edit manually. -->\n";

pub fn render() -> Result<String, String> {
    let ledger = super::coverage::load().map_err(|error| error.to_string())?;
    let mut output = String::from("# Supported Coding Standards\n\n");
    output.push_str(HEADER);
    output.push_str("\n| Section | Status | Mechanism | Languages | Limitations |\n| --- | --- | --- | --- | --- |\n");
    for section in ledger.sections {
        output.push_str(&format!(
            "| {} | {} | {} | {} | {} |\n",
            escape(&section.heading),
            section.status,
            section.mechanism,
            escape(&section.supported_languages.join(", ")),
            escape(&section.limitations),
        ));
    }
    Ok(output)
}

pub fn write(output: &Path, check: bool) -> Result<(), String> {
    let rendered = render()?;
    if check {
        let existing = std::fs::read_to_string(output)
            .map_err(|error| format!("read generated docs ({error})"))?;
        if existing != rendered {
            return Err(format!("generated docs are stale: {}", output.display()));
        }
        return Ok(());
    }
    if let Some(parent) = output.parent() {
        std::fs::create_dir_all(parent).map_err(|error| format!("create docs parent ({error})"))?;
    }
    let temp = output.with_extension("lgtm.tmp");
    std::fs::write(&temp, rendered).map_err(|error| format!("write generated docs ({error})"))?;
    std::fs::rename(&temp, output).map_err(|error| format!("publish generated docs ({error})"))?;
    Ok(())
}

fn escape(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_matrix_comes_from_coverage_ledger() {
        let rendered = render().expect("docs render");
        assert!(rendered.starts_with("# Supported Coding Standards"));
        assert!(rendered.contains("Non-Negotiable Rules"));
        assert!(rendered.contains("<!-- Generated by"));
    }
}
