//! Embedded rule documents used for coverage and heading accounting.

/// Every embedded rule document, including prose-only path-scoped files.
pub const RULE_DOCUMENT_SOURCES: &[(&str, &str)] = &[
    (
        "templates/claude-rules/CLAUDE.md",
        include_str!("../../templates/claude-rules/CLAUDE.md"),
    ),
    (
        "templates/claude-rules/rules/anti-slop.md",
        include_str!("../../templates/claude-rules/rules/anti-slop.md"),
    ),
    (
        "templates/claude-rules/rules/c-cpp.md",
        include_str!("../../templates/claude-rules/rules/c-cpp.md"),
    ),
    (
        "templates/claude-rules/rules/code-organization.md",
        include_str!("../../templates/claude-rules/rules/code-organization.md"),
    ),
    (
        "templates/claude-rules/rules/config.md",
        include_str!("../../templates/claude-rules/rules/config.md"),
    ),
    (
        "templates/claude-rules/rules/csharp.md",
        include_str!("../../templates/claude-rules/rules/csharp.md"),
    ),
    (
        "templates/claude-rules/rules/error-handling.md",
        include_str!("../../templates/claude-rules/rules/error-handling.md"),
    ),
    (
        "templates/claude-rules/rules/go.md",
        include_str!("../../templates/claude-rules/rules/go.md"),
    ),
    (
        "templates/claude-rules/rules/infrastructure.md",
        include_str!("../../templates/claude-rules/rules/infrastructure.md"),
    ),
    (
        "templates/claude-rules/rules/jvm.md",
        include_str!("../../templates/claude-rules/rules/jvm.md"),
    ),
    (
        "templates/claude-rules/rules/naming.md",
        include_str!("../../templates/claude-rules/rules/naming.md"),
    ),
    (
        "templates/claude-rules/rules/observability.md",
        include_str!("../../templates/claude-rules/rules/observability.md"),
    ),
    (
        "templates/claude-rules/rules/performance.md",
        include_str!("../../templates/claude-rules/rules/performance.md"),
    ),
    (
        "templates/claude-rules/rules/patterns/core.md",
        include_str!("../../templates/claude-rules/rules/patterns/core.md"),
    ),
    (
        "templates/claude-rules/rules/patterns/go.md",
        include_str!("../../templates/claude-rules/rules/patterns/go.md"),
    ),
    (
        "templates/claude-rules/rules/patterns/python.md",
        include_str!("../../templates/claude-rules/rules/patterns/python.md"),
    ),
    (
        "templates/claude-rules/rules/patterns/react.md",
        include_str!("../../templates/claude-rules/rules/patterns/react.md"),
    ),
    (
        "templates/claude-rules/rules/patterns/rust.md",
        include_str!("../../templates/claude-rules/rules/patterns/rust.md"),
    ),
    (
        "templates/claude-rules/rules/patterns/sql.md",
        include_str!("../../templates/claude-rules/rules/patterns/sql.md"),
    ),
    (
        "templates/claude-rules/rules/patterns/testing.md",
        include_str!("../../templates/claude-rules/rules/patterns/testing.md"),
    ),
    (
        "templates/claude-rules/rules/patterns/typescript.md",
        include_str!("../../templates/claude-rules/rules/patterns/typescript.md"),
    ),
    (
        "templates/claude-rules/rules/python.md",
        include_str!("../../templates/claude-rules/rules/python.md"),
    ),
    (
        "templates/claude-rules/rules/react.md",
        include_str!("../../templates/claude-rules/rules/react.md"),
    ),
    (
        "templates/claude-rules/rules/rust.md",
        include_str!("../../templates/claude-rules/rules/rust.md"),
    ),
    (
        "templates/claude-rules/rules/security.md",
        include_str!("../../templates/claude-rules/rules/security.md"),
    ),
    (
        "templates/claude-rules/rules/shell.md",
        include_str!("../../templates/claude-rules/rules/shell.md"),
    ),
    (
        "templates/claude-rules/rules/sql.md",
        include_str!("../../templates/claude-rules/rules/sql.md"),
    ),
    (
        "templates/claude-rules/rules/testing.md",
        include_str!("../../templates/claude-rules/rules/testing.md"),
    ),
    (
        "templates/claude-rules/rules/typescript.md",
        include_str!("../../templates/claude-rules/rules/typescript.md"),
    ),
    (
        "templates/claude-rules/rules/web-ui.md",
        include_str!("../../templates/claude-rules/rules/web-ui.md"),
    ),
];
