//! Codex project-hook configuration merge.

use super::InitError;
use super::config::ValidatedSettings;
use super::fs::read_if_exists;
use super::settings::commands_match;
use serde::Deserialize;
use serde_json::{Map, Value, json};
use std::path::Path;

const CODEX_HOOKS: [HookWiring; 5] = [
    HookWiring {
        event: "SessionStart",
        command: "lgtm hook session-start --adapter codex",
        matcher: None,
    },
    HookWiring {
        event: "UserPromptSubmit",
        command: "lgtm hook user-prompt-submit --adapter codex",
        matcher: None,
    },
    HookWiring {
        event: "PreToolUse",
        command: "lgtm hook pre-tool-use --adapter codex",
        matcher: Some("apply_patch|Edit|Write|exec_command|unified_exec|Bash"),
    },
    HookWiring {
        event: "PostToolUse",
        command: "lgtm hook post-tool-use --adapter codex",
        matcher: Some("apply_patch|Edit|Write|exec_command|unified_exec|Bash"),
    },
    HookWiring {
        event: "Stop",
        command: "lgtm hook stop --adapter codex",
        matcher: None,
    },
];

struct HookWiring {
    event: &'static str,
    command: &'static str,
    matcher: Option<&'static str>,
}

pub(super) fn render_hooks(validated: ValidatedSettings) -> Option<Vec<u8>> {
    let existing = validated.unwrap_or_default();
    let merged = merge_hooks(&existing);
    if merged == existing {
        return None;
    }
    let mut serialized = serde_json::to_string_pretty(&Value::Object(merged))
        .expect("Codex hooks map serializes as a JSON object");
    serialized.push('\n');
    Some(serialized.into_bytes())
}

pub(super) fn merge_hooks(existing: &Map<String, Value>) -> Map<String, Value> {
    let mut merged = existing.clone();
    let hooks_entry = merged
        .entry("hooks")
        .or_insert_with(|| Value::Object(Map::new()));
    let Value::Object(hooks) = hooks_entry else {
        return merged;
    };
    for wiring in &CODEX_HOOKS {
        let entries = hooks
            .entry(wiring.event.to_string())
            .or_insert_with(|| Value::Array(Vec::new()));
        let Value::Array(entries) = entries else {
            continue;
        };
        match entries
            .iter_mut()
            .find(|entry| entry_runs_command(entry, wiring.command))
        {
            Some(entry) => reconcile_matcher(entry, wiring.matcher),
            None => entries.push(hook_entry(wiring)),
        }
    }
    merged
}

#[derive(Debug, Default, Deserialize)]
struct ExecPolicyConfig {
    #[serde(default)]
    prohibited_commands: Vec<Vec<String>>,
    #[serde(default)]
    prohibited_paths: Vec<String>,
}

/// Compile explicit repository command prefixes into a Codex rules file.
///
/// Path rules remain in LGTM's PreToolUse gate because Codex `prefix_rule`
/// matches command argv, not filesystem targets. They are retained as comments
/// in the generated file so the limitation is visible without pretending the
/// second net enforces something it cannot.
pub(super) fn render_execpolicy(
    root: &Path,
    rules_path: &Path,
) -> Result<(Option<Vec<u8>>, Vec<String>), InitError> {
    let source_path = root.join(".lgtm/execpolicy.json");
    let Some(contents) = read_if_exists(&source_path)? else {
        return Ok((None, Vec::new()));
    };
    let config: ExecPolicyConfig =
        serde_json::from_str(&contents).map_err(|error| InitError::MalformedExecPolicy {
            path: source_path.clone(),
            reason: error.to_string(),
        })?;
    validate_execpolicy(&config).map_err(|reason| InitError::MalformedExecPolicy {
        path: source_path,
        reason,
    })?;
    let mut notes =
        vec!["Codex execpolicy is defense-in-depth; lgtm hooks remain authoritative".to_string()];
    if !config.prohibited_paths.is_empty() {
        notes.push(
            "Codex execpolicy does not match filesystem paths; prohibited_paths remain enforced by lgtm"
                .to_string(),
        );
    }
    if rules_path.exists() {
        notes.push(format!(
            "preserving existing {}; remove it explicitly to regenerate lgtm rules",
            rules_path.display()
        ));
        return Ok((None, notes));
    }
    if config.prohibited_commands.is_empty() {
        return Ok((None, notes));
    }
    let mut output = String::new();
    output.push_str("# Generated by lgtm from .lgtm/execpolicy.json\n");
    for command in config.prohibited_commands {
        let pattern =
            serde_json::to_string(&command).map_err(|error| InitError::MalformedExecPolicy {
                path: root.join(".lgtm/execpolicy.json"),
                reason: format!("serialize command prefix ({error})"),
            })?;
        output.push_str(&format!(
            "prefix_rule(pattern={pattern}, decision=\"deny\")\n"
        ));
    }
    for path in config.prohibited_paths {
        output.push_str(&format!("# lgtm path rule (hook-enforced): {path}\n"));
    }
    Ok((Some(output.into_bytes()), notes))
}

/// Report whether Codex's external config appears to contain a trust record
/// for this project's hook file. This is intentionally advisory: LGTM never
/// writes Codex's private trust state or treats a stale hash as trusted.
pub(super) fn trust_note(hooks_path: &Path) -> String {
    let Some(home) = std::env::var_os("CODEX_HOME")
        .map(std::path::PathBuf::from)
        .or_else(|| {
            std::env::var_os("HOME").map(|home| std::path::PathBuf::from(home).join(".codex"))
        })
    else {
        return codex_trust_note("trust state unavailable; review `/hooks`");
    };
    let config = home.join("config.toml");
    let Ok(metadata) = std::fs::metadata(&config) else {
        return codex_trust_note("no trust record detected; review `/hooks`");
    };
    if metadata.len() > 512 * 1_024 {
        return codex_trust_note("trust config too large to inspect; review `/hooks`");
    }
    let Ok(contents) = std::fs::read_to_string(config) else {
        return codex_trust_note("trust state unreadable; review `/hooks`");
    };
    let path = hooks_path.to_string_lossy();
    let has_record = contents.contains(path.as_ref()) && contents.contains("trusted_hash");
    if has_record {
        codex_trust_note("existing trust record detected; verify it in `/hooks`")
    } else {
        codex_trust_note("no matching trust record detected; review `/hooks`")
    }
}

fn codex_trust_note(status: &str) -> String {
    format!(
        "Codex SHA-256-pins hook definitions; {status}. Trust state is managed by Codex outside this repository and is not auto-approved by init."
    )
}

fn validate_execpolicy(config: &ExecPolicyConfig) -> Result<(), String> {
    if config.prohibited_commands.len() > 256 || config.prohibited_paths.len() > 256 {
        return Err("maximum 256 prohibited commands and paths".to_string());
    }
    for command in &config.prohibited_commands {
        if command.is_empty() || command.len() > 32 {
            return Err("command prefixes must contain 1..=32 argv items".to_string());
        }
        if command
            .iter()
            .any(|item| item.is_empty() || item.len() > 4096 || item.chars().any(char::is_control))
        {
            return Err("command prefixes contain an invalid argv item".to_string());
        }
    }
    for path in &config.prohibited_paths {
        if path.is_empty()
            || path.len() > 4096
            || path.starts_with('/')
            || path.split('/').any(|part| part == "..")
            || path.chars().any(char::is_control)
        {
            return Err("prohibited_paths contains an invalid relative path".to_string());
        }
    }
    Ok(())
}

fn entry_runs_command(entry: &Value, expected: &str) -> bool {
    entry
        .get("hooks")
        .and_then(Value::as_array)
        .is_some_and(|hooks| {
            hooks.iter().any(|hook| {
                hook.get("type").and_then(Value::as_str) == Some("command")
                    && hook
                        .get("command")
                        .and_then(Value::as_str)
                        .is_some_and(|found| commands_match(found, expected))
            })
        })
}

fn reconcile_matcher(entry: &mut Value, matcher: Option<&str>) {
    let Value::Object(entry) = entry else {
        return;
    };
    match matcher {
        Some(matcher) => {
            entry.insert("matcher".to_string(), Value::String(matcher.to_string()));
        }
        None => {
            entry.remove("matcher");
        }
    }
}

fn hook_entry(wiring: &HookWiring) -> Value {
    let inner = json!({
        "type": "command",
        "command": wiring.command,
    });
    match wiring.matcher {
        Some(matcher) => json!({ "matcher": matcher, "hooks": [inner] }),
        None => json!({ "hooks": [inner] }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn merge_adds_all_codex_events_and_matchers() {
        let merged = merge_hooks(&Map::new());
        let hooks = merged["hooks"].as_object().expect("hooks object");
        assert_eq!(hooks.len(), 5);
        assert_eq!(
            hooks["PreToolUse"][0]["matcher"],
            "apply_patch|Edit|Write|exec_command|unified_exec|Bash"
        );
        assert_eq!(
            hooks["PreToolUse"][0]["hooks"][0]["command"],
            "lgtm hook pre-tool-use --adapter codex"
        );
    }

    #[test]
    fn merge_is_idempotent_and_preserves_unrelated_values() {
        let existing = json!({
            "permissions": {"allow": ["Bash"]},
            "hooks": {
                "Stop": [{"hooks": [{"type": "command", "command": "other"}]}]
            }
        });
        let existing = existing.as_object().expect("object").clone();
        let once = merge_hooks(&existing);
        let twice = merge_hooks(&once);
        assert_eq!(once, twice);
        assert_eq!(once["permissions"], json!({"allow": ["Bash"]}));
        assert_eq!(once["hooks"]["Stop"].as_array().unwrap().len(), 2);
    }

    #[test]
    fn merge_reconciles_path_qualified_lgtm_matcher() {
        let existing = json!({
            "hooks": {
                "PreToolUse": [{
                    "matcher": "Bash",
                    "hooks": [{
                        "type": "command",
                        "command": "/usr/local/bin/lgtm hook pre-tool-use --adapter codex"
                    }]
                }]
            }
        });
        let merged = merge_hooks(existing.as_object().expect("object"));
        assert_eq!(
            merged["hooks"]["PreToolUse"][0]["matcher"],
            "apply_patch|Edit|Write|exec_command|unified_exec|Bash"
        );
        assert_eq!(merged["hooks"]["PreToolUse"].as_array().unwrap().len(), 1);
    }

    #[test]
    fn execpolicy_renders_denies_and_documents_path_limits() {
        let root = std::env::temp_dir().join(format!("lgtm-execpolicy-{}", std::process::id()));
        std::fs::create_dir_all(&root).expect("temp root");
        std::fs::create_dir_all(root.join(".lgtm")).expect("lgtm config dir");
        std::fs::write(
            root.join(".lgtm/execpolicy.json"),
            r#"{"prohibited_commands":[["git","reset","--hard"]],"prohibited_paths":["secrets/**"]}"#,
        )
        .expect("execpolicy fixture");
        let rules = root.join(".codex/rules/lgtm.rules");
        let (rendered, notes) = render_execpolicy(&root, &rules).expect("execpolicy renders");
        let rendered = String::from_utf8(rendered.expect("rules output")).expect("UTF-8 rules");
        assert!(rendered.contains("prefix_rule(pattern=[\"git\",\"reset\",\"--hard\"]"));
        assert!(rendered.contains("hook-enforced"));
        assert!(notes.iter().any(|note| note.contains("defense-in-depth")));
        let _ = std::fs::remove_dir_all(root);
    }
}
